#!/bin/bash
# Monitoring Commands for HyperLogic RAG V2 Test Run

echo "=================================================="
echo "HYPERLOGIC RAG V2 - MONITORING DASHBOARD"
echo "=================================================="
echo ""

echo "📊 JOB STATUS:"
echo "---"
squeue -u $USER -o "%.10i %.15j %.8T %.10M %.6D %.10R"
echo ""

echo "📈 LATEST PROGRESS (Live):"
echo "---"
tail -3 /home/dangnh3/MICCAI2026/HyperLogicRAG/logs/hyperlogic_v2test-2302.err 2>/dev/null || echo "Log chưa sẵn sàng"
echo ""

echo "🔍 LOGIC LOSS TRAJECTORY (every 500 batches):"
echo "---"
grep "BATCH.*DEBUG" /home/dangnh3/MICCAI2026/HyperLogicRAG/logs/hyperlogic_v2test-2302.out 2>/dev/null | tail -5 || echo "Chưa có debug logs"
echo ""

echo "=================================================="
echo "LIVE MONITORING COMMANDS:"
echo "=================================================="
echo ""
echo "1. Theo dõi progress bar LIVE:"
echo "   tail -f /home/dangnh3/MICCAI2026/HyperLogicRAG/logs/hyperlogic_v2test-2302.err"
echo ""
echo "2. Xem debug logs (entity_probs, logic loss):"
echo "   tail -f /home/dangnh3/MICCAI2026/HyperLogicRAG/logs/hyperlogic_v2test-2302.out"
echo ""
echo "3. Kiểm tra job có bị lỗi không:"
echo "   sacct -j 2302 --format=JobID,State,Elapsed,ExitCode"
echo ""
echo "4. Quick check (chạy script này):"
echo "   bash scripts/monitor_v2test.sh"
echo ""
echo "=================================================="
echo "SUCCESS CRITERIA:"
echo "=================================================="
echo "✅ Logic loss > 0.01 (currently showing ~0.25)"
echo "✅ Entity probs: min > 0.05"
echo "✅ No NaN or crashes"
echo "✅ Gen loss decreasing"
echo ""
